//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fs.Erp.Core.AppServiceContract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fs.Erp.Core.AppServiceContract.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุรหัสผ่านปัจจุบัน.
        /// </summary>
        public static string ChangePassword_001 {
            get {
                return ResourceManager.GetString("ChangePassword_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุรหัสผ่านใหม่.
        /// </summary>
        public static string ChangePassword_002 {
            get {
                return ResourceManager.GetString("ChangePassword_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณายืนยันรหัสผ่านใหม่.
        /// </summary>
        public static string ChangePassword_003 {
            get {
                return ResourceManager.GetString("ChangePassword_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Unfinished , Please contact your admin !.
        /// </summary>
        public static string MSG_ErrorResetPasss {
            get {
                return ResourceManager.GetString("MSG_ErrorResetPasss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External login is duplicated..
        /// </summary>
        public static string MSG_ExternalLogin_Duplicate {
            get {
                return ResourceManager.GetString("MSG_ExternalLogin_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to must be later or equal to date from..
        /// </summary>
        public static string MSG_INVALID_DATETIME {
            get {
                return ResourceManager.GetString("MSG_INVALID_DATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is duplicated..
        /// </summary>
        public static string MSG_Login_Duplicate {
            get {
                return ResourceManager.GetString("MSG_Login_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove , ACL less than 1 item..
        /// </summary>
        public static string MSG_RemoveAllACLItem {
            get {
                return ResourceManager.GetString("MSG_RemoveAllACLItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุ รหัสบทบาท ความยาวระหว่าง {3} - {5} ตัวอักษร.
        /// </summary>
        public static string MSG_ROLEOPERATION_001 {
            get {
                return ResourceManager.GetString("MSG_ROLEOPERATION_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกรหัสการดำเนินการ.
        /// </summary>
        public static string MSG_ROLEOPERATION_002 {
            get {
                return ResourceManager.GetString("MSG_ROLEOPERATION_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope description length must be between {3} and {5}. .
        /// </summary>
        public static string MSG_SCOPE_001 {
            get {
                return ResourceManager.GetString("MSG_SCOPE_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope name length must be between {3} and {5}..
        /// </summary>
        public static string MSG_SCOPE_002 {
            get {
                return ResourceManager.GetString("MSG_SCOPE_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope type must be digit only..
        /// </summary>
        public static string MSG_SCOPE_003 {
            get {
                return ResourceManager.GetString("MSG_SCOPE_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a Role for this scope..
        /// </summary>
        public static string MSG_SCOPEROLEGROUP_001 {
            get {
                return ResourceManager.GetString("MSG_SCOPEROLEGROUP_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a Group for this scope..
        /// </summary>
        public static string MSG_SCOPEROLEGROUP_002 {
            get {
                return ResourceManager.GetString("MSG_SCOPEROLEGROUP_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User code is duplicated..
        /// </summary>
        public static string MSG_UserCode_Duplicate {
            get {
                return ResourceManager.GetString("MSG_UserCode_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุ รหัส ความยาวระหว่าง {3} - {5} ตัวอักษร.
        /// </summary>
        public static string MSG001 {
            get {
                return ResourceManager.GetString("MSG001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุ ชื่อ ความยาวระหว่าง {3} - {5} ตัวอักษร.
        /// </summary>
        public static string MSG002 {
            get {
                return ResourceManager.GetString("MSG002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุ รายละเอียด ความยาวระหว่าง {3} - {5} ตัวอักษร.
        /// </summary>
        public static string MSG003 {
            get {
                return ResourceManager.GetString("MSG003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุ Login ความยาวระหว่าง {3} - {5} ตัวอักษร.
        /// </summary>
        public static string MSG004 {
            get {
                return ResourceManager.GetString("MSG004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุ รหัสผ่าน ความยาวระหว่าง {3} - {5} ตัวอักษร.
        /// </summary>
        public static string MSG005 {
            get {
                return ResourceManager.GetString("MSG005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุ E-mail ความยาวระหว่าง {3} - {5} ตัวอักษร.
        /// </summary>
        public static string MSG006 {
            get {
                return ResourceManager.GetString("MSG006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyCode length must be between {3} and {5}..
        /// </summary>
        public static string MSG007 {
            get {
                return ResourceManager.GetString("MSG007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty length must be between {3} and {5}..
        /// </summary>
        public static string MSG008 {
            get {
                return ResourceManager.GetString("MSG008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount length must be between {3} and {5}..
        /// </summary>
        public static string MSG009 {
            get {
                return ResourceManager.GetString("MSG009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationCode length must be between {3} and {5}..
        /// </summary>
        public static string MSG010 {
            get {
                return ResourceManager.GetString("MSG010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select date..
        /// </summary>
        public static string MSG011 {
            get {
                return ResourceManager.GetString("MSG011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select Currency..
        /// </summary>
        public static string MSG012 {
            get {
                return ResourceManager.GetString("MSG012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select Formula..
        /// </summary>
        public static string MSG013 {
            get {
                return ResourceManager.GetString("MSG013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required..
        /// </summary>
        public static string MSG014 {
            get {
                return ResourceManager.GetString("MSG014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select operation..
        /// </summary>
        public static string MSG015 {
            get {
                return ResourceManager.GetString("MSG015", resourceCulture);
            }
        }
    }
}
